### ISSUE TITLE
Consider storing axis of separation in nodes when splitting

### ISSUE THREAD

**Issue by mquander** [gkjohnson/threejs-fast-raycast#34]
Physically Based Rendering had this great suggestion for improving raycasting performance. Ordinarily, if you want to find only the closest intersection for your ray, you need to test your ray against both bounding volumes at each level of the tree hierarchy, and take whichever has the intersection with the closest distance, because it could intersect both. But if you use an SAH strategy and you remember at each node which axis was used for splitting, you can look at where the ray is coming from with respect to the split plane and you know right away which child bounding volume must have the closest intersection, if it intersects that bounding volume at all. You may not have to even look at the other one.

Of course this will cost a little memory but it sounds like it might improve raycasting `firstHitOnly` performance very substantially.

**Comment by gkjohnson** [comment]
I believe we're already doing this in `raycastFirst` here:
https://github.com/gkjohnson/threejs-fast-raycast/blob/master/lib/MeshBVHNode.js#L64

It's not exactly the same approach but I believe it has the same effect and doesn't take any extra memory. Basically we check which node is closest to the ray and traverse that first. If no triangle is hit then we check the other node.

We don't do this in the regular `raycast` function, though -- I don't think there's a reason to?
